### ISSUE TITLE
[UNIX] ARNetWorkAL Error : Wifi generic error

### ISSUE THREAD

**Issue by CesarRN** [Parrot-Developers/Samples#22]
Hello all.

I´m testing the Unix example on a Mac.
I can run the example, but I obtain this error:

ARNETWORKAL_WifiNetwork_Bind:551 - ARNETWORKAL_WifiNetwork_Bind: error = -1
ARNetWorkAL Error : Wifi generic error

What´s the problem?

Thanks in advance.

**Comment by vignesh02** [comment]
CesarRN,

Have you connected to drone WIFI before running the example?

**Comment by CesarRN** [comment]
Yes,of course.

I can connect with my MacBookPro with telnet and I can access to ftp folder, ..., the connection between Mac and BeBop by WIFI is ok.

What can should I do?

Thanks

**Comment by djavan-bertrand** [comment]
Hi CesarRN, 

This error is due to the port on which you are trying to read which is already busy.
Do you have two instances of this sample running at the same time on your computer ? 
If not, you can try to change the value of BD_D2C_PORT. This will change the reading port. 

Hope this helps, 
Djavan

**Comment by CesarRN** [comment]
Hello djavan-bertrand, I have the defaults values:

#define TAG "BebopDroneReceiveStream"
#define BD_IP_ADDRESS "192.168.42.1"
#define BD_DISCOVERY_PORT 44444
#define BD_C2D_PORT 54321 // should be read from Json
#define BD_D2C_PORT 43210

Do you detect any error?

Thanks!

**Comment by CesarRN** [comment]
Hi again.

I test with two differents values and the error is the same.

#define BD_D2C_PORT 41111 //43210

 :'(

Thanks!
