### ISSUE TITLE
unix c sample for Rolling Spider

### ISSUE THREAD

**Issue by lazybean** [Parrot-Developers/Samples#31]
Hey,
I wanted to play with the rolling spider but there is no c sample for it.

I tried to start with the JumpingSumoPiloting and modify it, but I have trouble to deal with BLE. (and my c is old)

A sample for that would be highly appreciated!

**Comment by djavan-bertrand** [comment]
Hi, 

You have a contribution sample which deals with [RollingSpider on MacOS system](https://github.com/ARDroneSDK3/Samples/tree/master/Contributions/OSX). You can use this sample and change the library used to handle the BLE connection (on MacOS it is CoreBluetooth).

Best regards, 
Djavan

**Comment by djavan-bertrand** [comment]
In fact, this sample is in Objective C, so it won't help.

So you will need to use a library that handles Bluetooth Low Energy and adapt the JumpingSumo sample to connect to a RollingSpider (for this last part, you can see the Rolling Spider samples on iOS, Android or MacOS).

**Comment by lazybean** [comment]
Thanks for the help!
I'll look for BLE lib.

**Comment by AzemaBaptiste** [comment]
Hi,
Do you achieve to connect the Rolling Spider to your computer through SDK ? 
I am also looking for an unix sample.

Thanks
