### ISSUE TITLE
Rotate the drone to magnetic north

### ISSUE THREAD

**Issue by Zepheus** [Parrot-Developers/Samples#32]
Hello,

I am trying to make the Bebop drone point towards the magnetic north. From my experiments the yaw value read from the magnetometer in the AttitudeChanged payload is relative to the orientation when the drone is powered on. Is there any way to read the absolute heading using a simple sensor read? There also seems to be a lot of jitter on this value (e.g. rotating the drone 360 degrees results in an error offset of around 40-50 degrees, even right after calibration).

The only way I can calibrate it right now is by reading GPS, moving forwards and calculate the relative heading between both readings, which eventually could give me an absolute heading.

Thanks in advance

**Comment by ObieChen** [comment]
Hello,

I got same question here. All I know is that there's a magnetometer on Bebop, but none had mentioned out how to get it. According to the forum, it said that it is not allowed to get raw sensor value unless you use callback APIs. Actually, there is no magnetometer-related callbacks during my search. Really frustrating can't even apply absolute control on Bebop. Plz let me know if I am wrong. Any help will be appreciated. 

Best, 
Obie

**Comment by Zepheus** [comment]
@ObieChen you can read the magnetometer from the AttitudeChanged callback and read the yaw values, but main issue is that this value is relative to takeoff (not raw sensor value) and also contains quite a lot of jitter.
I have not tested this using the official SDK since I am writing my own, but it should be ARCOMMANDS_Decoder_SetARDrone3PilotingStateAttitudeChangedCallback

Hopefully this helps.

**Comment by ObieChen** [comment]
@Zepheus Thanks for your reply. I am starting using the AttitudeChange callback to get what I want. Looks like there's no any other method to retrieve magnetometer correctly. I am quite curious about how you start your own stuff. Mind if I ask about it? Really want to start on my own as well.

Big thanks!

**Comment by Zepheus** [comment]
@ObieChen most of the analysis for communication is documented here: https://github.com/Zepheus/ardrone3-pcap/blob/master/README.md

For absolute control, I think it is possible to read out sensor values right from /sys and /dev using telnet. I will look into it. Eventually you can cross-compile a daemon that accepts your requests and forwards these to the device drivers yourself.

As for the framework, me and my colleagues are still working on it with the goal of making it open-source, but we are still working on stability and code quality before release. (It is based on Akka and has a REST-full interface).
