### ISSUE TITLE
Android BebopDronePiloting Sample's libraries 

### ISSUE THREAD

**Issue by Roxside** [Parrot-Developers/Samples#34]
Hi ,
I tried the Android BebopDronePiloting on ANdroid Studio  but it seems that it's not working because  jar libraries are corrupted. Does someone solve this problem and make a working project on android studio.If so i would be apreciated 
Thanks.

**Comment by djavan-bertrand** [comment]
Hi Roxside, 
Did you compile the SDK by running the SDKBuild.py script ?
If no, please refer to [this installation documentation](https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL).

Thanks, 
Djavan

**Comment by Roxside** [comment]
Hi Djavan,

Yes I already did those steps if your android project works , can you send me your libraries or .apk file would be good too .

Thanks,
Roxside

**Comment by djavan-bertrand** [comment]
Hi, 
Did you clone the Sample repository on your own ? Did you move the sample folder from its original position ?
BebopDronePiloting folder should be let here : 

```
YourFolder
      |_ARSDKBuildUtils
      |_libARCommands
      |_libARMedia
      |_ ...
      |_ Samples
              |_Android
                     |_BebopDronePiloting
```
Sending you an apk file won't be very useful, I think.

Maybe you can post the error to let us help you more accurately.

Best regards, 
Djavan
