### ISSUE TITLE
Callback for mini drone speed 

### ISSUE THREAD

**Issue by Ericein** [Parrot-Developers/Samples#35]
Hey, 
is there a call to get mini drone speed (x axis)?

couldn't find it in the SDK.

Thx

E

**Comment by Ericein** [comment]
Anyone?

**Comment by djavan-bertrand** [comment]
Hi, 

You only have this piece of information on the Bebop, not on the Rolling Spider.

Regards, 
Djavan

**Comment by Ericein** [comment]
hi, Djavan Thanks of your replay, 
I’m building some academic project involving  anti collision algorithm , so I wanted to use the speed callback to determine if drone hit something, 
After I understand its not possible with MiniDrone I look the Emergency state (ARCOMMANDS_Decoder_SetMiniDronePilotingStateFlyingStateChangedCallback), but the problem using this method, that the engines cutoff on Emergency state,
So my question is:
is there’s a way to get the Emergency state without the engine turn off?
any other suggestion to approach the problem?

Thx
 E
