### ISSUE TITLE
Saving Raw frame to jpg  [BebopDroneDecodeStream]

### ISSUE THREAD

**Issue by dk683** [Parrot-Developers/Samples#38]
Thank you @djavan-bertrand and Parrot team for providing a new sample for decoding h264 frame (https://github.com/ARDroneSDK3/Samples/tree/master/Unix/BebopDroneDecodeStream)!
However, the sample does not yet provide how I could save raw frame to jpg image. Could you help me with this? I deeply appreciate your help!

**Comment by djavan-bertrand** [comment]
Hi, 

this [SO thread](http://stackoverflow.com/questions/9364693/covert-raw-image-buffer-into-jpeg-using-libavcodec) might help you.

Best regards, 
Djavan
