### ISSUE TITLE
What is the command to take a picture in the BeBop?

### ISSUE THREAD

**Issue by CesarRN** [Parrot-Developers/Samples#42]
Hello all.

In the FreeFlight 3 app there is a button to take a photo.

I would like to create the same button in my app, but I can´t find the command
(something like ARDrone3 ....)

Thanks!

**Comment by djavan-bertrand** [comment]
Hi, 
the command is ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture.
You can pass 0 as parameter for the mass storage id.

Best regards, 
Djavan

**Comment by CesarRN** [comment]
Thanks! Djavan, function developed in my app  :)

Kind regards.
