### ISSUE TITLE
Connect multipule drones to one device

### ISSUE THREAD

**Issue by Ericein** [Parrot-Developers/Samples#47]
Hi,
Is it possible to connect multiple drones (rolling spiders) to one device (iOS) to control them all together?

Thx

Eric

**Comment by Ericein** [comment]
Anyone?

**Comment by djavan-bertrand** [comment]
Hi, 

No, the SDK is not designed to enable the BLE multiple connections. If you really need to, you can modify the SDK sources. 
The first block I see is that we use a BLE manager which is a singleton (in libARSAL : ARSAL_BLEManager), this is why we can connect to only one RollingSpider. 

Best regards, 
Djavan
