### ISSUE TITLE
Unix/OS X Video stream and pilot for Parrot BeBop

### ISSUE THREAD

**Issue by bentito** [Parrot-Developers/Samples#48]
It seems like there was close to this solution back in February, it's been suggested to merge Sumo piloting sample with BeBopStreaming sample to get this to work, and there seems to be certain things you have to do to make it actually work with decent frame rate and still control Bebop.

But has anyone either at Parrot, or others, released a sample that both pilots and streams for Unix/OS X? Would be really great if this was released because I'm sure this is what many people want. 

I am going to set to work on such a sample and will release it when I am done, but hoping someone might save me some time by having done it already and sharing.

**Comment by bentito** [comment]
Okay, well after that overwhelming response.... Here you go folks, this is as far as I'm going with the C version http://pastebin.com/JnKYGWpJ 

It streams video, takes off and lands, never worked out the PCMD to pilot for real. Be really nice to have docs for the 3.0 SDK.

Stopping further work on the C version for Unix since I see there is a supposedly working Android sample of BeBop piloting. I'll be stripping the Android out of that to give myself a nice Java version to work with further for Unix/OS X.

**Comment by djavan-bertrand** [comment]
Hi, 
I'm really sorry for the late answer. 
The [BebopDroneDecodeStream](https://github.com/Parrot-Developers/Samples/tree/master/Unix/BebopDroneDecodeStream) sample does receive stream, decode it, and let you pilot it.

Best regards, 
Djavan

**Comment by bentito** [comment]
Oh man, okay, sorry, didn't even realize something named 'decode' could be
what I was looking for.

Brett Tofel
(802) 765-0440
