### ISSUE TITLE
Graphics driver 

### ISSUE THREAD

**Issue by alexcherpi** [Parrot-Developers/Samples#49]
HI,

I have linux ubuntu 12.04 LTS with the basic graphic card (Intel) and and other one (Nvidia K2100).
How to be sure that the sample 'BebopDroneDecodeStream' is using the Nvidia graphic card for the h264 decoding and the mplayer display ? Because it lags a log while running this sample.
Thanks,
Alex

**Comment by djavan-bertrand** [comment]
Hi, 

This sample is using ffmpeg to decode the video. As far as I know it will depend on your installation of ffmpeg. There are certainly some compilation config that will enable the hardware decoding.
Maybe see [here](https://trac.ffmpeg.org/wiki/HWAccelIntro).
Best regards, 
Djavan

**Comment by alexcherpi** [comment]
Are you planning to release the SDK for windows ?
But have you already seen lags during the video streaming using your SDK on ubuntu (lenovo W540) ?

**Comment by alexcherpi** [comment]
Do you think the SDK will run faster on OSX than on Linux?

**Comment by djavan-bertrand** [comment]
Hi, 

You could experience some lags during video streaming, it is certainly due to Wifi interferences. If it is the case, try to switch your drone's in a 5Ghz band (you can use FreeFlight3 to do that).
I don't think it will be faster on OSX.

Regards, 
Djavan

**Comment by alexcherpi** [comment]
I'm using a Lenovo W540 (Processor: Intel® Core™ i7-4800MQ CPU @ 2.70GHz × 8, Graphcis: Quadro K2100M) with linux/ubuntu 14.04 LTS.
The video streaming lags during 'BebopDroneDecodeStream' execution.
With the 'htop' command I see that one core of the CPU is always at maximum, whereas the GPU is only at 5% of use (the program doesn't use it then).
Did you plan to change this code to use the GPU or more threads ?
Thanks, Alex

**Comment by alexcherpi** [comment]
In fact, for me 'BebopDroneDecodeStream' is slower than 'BebopDroneReceiveStream' because all the threads are concentrated on one core of the CPU whereas with 'BebopDroneReceiveStream' they are spread.

**Comment by alexcherpi** [comment]
@djavan-bertrand 
BebopDroneDecodeStream is the fastest has sometimes jitters because it looks like all the processing is done on one core.. (one is at 100% while the others are at 10%) What do I have to do for that ?
