### ISSUE TITLE
Android missing files

### ISSUE THREAD

**Issue by ChristophMinnameier** [Parrot-Developers/Samples#5]
Hi,

I am trying to create a custom app to control the jumping sumo via android devices.
So far, I have accomplished to build your sources for Android (following https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL) and as expected ended up with some jar libs and the respective .so libs.
I created an android project in eclipse, included the libs and copied the android sample .java files (https://github.com/ARDroneSDK3/Samples/tree/master/Android) to my source folder, unfortunately ending up with a lot of missing files.

After reading the reported iOS issues, I am aware that I am expected to implement some of the classes myself. For some classes, (e.g. the Photo-/Video- RecordController) this makes sense, but for others I wonder wheter this was intended:

If I use the eclipse quick fix feature to resolve missing imports by creatíng all the missing classes and their respective functions I end up with 8 classes to implement:
ARRouter
ARRouterDiscoveryConnection
JumpingSumoPhotoRecordController
JumpingSumoVideoRecordController
DataCollectionUtils
DeviceUtils
ARFrame
ARStreamManager

Also I found no include for ARBundle, so I assume I am meant to create this class in the devicecontrollers package.

Finally, I guess the following imports in JumpingSumoDeviceController are misplaced:
import com.parrot.freeflight3.recordcontrollers.ARDrone3PhotoRecordController;
import com.parrot.freeflight3.recordcontrollers.ARDrone3VideoRecordController;
Afaik, the ARDrone3 is a different parrot drone right? Or does the 3 stand for SDK3 in this case?

Would you mind pointing out what the respective classes are meant to do or which router etc you expect me to wrap? At least I guess I am expected to provide my own router/binder etc? Is there a documentation i am simply missing? I didnt find anything useful in https://github.com/ARDroneSDK3/Docs which seems just to include the auto-generated API reference.

Thanks in advance!

**Comment by aiden56** [comment]
In addition to this, your twitter site mentioned that you'd be releasing working examples for all platforms in January - is this still going to be the case?

**Comment by cipriansofronia** [comment]
It would be nice if they would release an working sample for the JumpingSumo...  
Is there anyone who has the missing classes?? :D Please share with us :))
