### ISSUE TITLE
How to set better video settings, bigger width, height

### ISSUE THREAD

**Issue by bentito** [Parrot-Developers/Samples#51]
So using the Unix sample for BebopDecodeStream works pretty well. But one is left with seeing only a 640x368 width x height video. How can we get a better quality video?

**Comment by djavan-bertrand** [comment]
Hi, 

The streaming is set to these dimensions. To have a better video quality, you have to record the video and then download it. The recorded video is 1080p.

Regards, 
Djavan

**Comment by alexcherpi** [comment]
@bentito 
What is the latency you have ? And what are the performance of the computer you are running the 'BebopDecodeStream' sample ?

@djavan-bertrand 
The 'BebopDroneReceiveStream' use h.264 or MPEG compression ?

**Comment by bentito** [comment]
Fairly low latency since we're doing indoor programmatic control at the
moment. And the computer running the sample is a VirtualBox Ubuntu working
on a robust Mac Powerbook (4 cores, 8 with hypervisor) the VM guest has
access to all the host resources. Why do you ask? Are you thinking we could
stream better quality? I am...

-brett

Brett Tofel
(802) 765-0440

**Comment by alexcherpi** [comment]
I'm running a high-end computer (i7 4Ghz with nvidia 980GTX) dual-booted with linux and I have a latency of 380ms with 'BebopDroneReceiveStream'. So I was wondering what you have. I still have some problems to run 'BebopDecodeStream'.

**Comment by bentito** [comment]
Ah, how are you measuring the latency?

Brett Tofel
(802) 765-0440

**Comment by alexcherpi** [comment]
You film a running timer with the bebop and you take a picture of both the timer and the video feed-back at the same time and then compute the difference

**Comment by bentito** [comment]
Ok, using that methodology I get an average over a few takes of about
240ms. You think that should be higher?

-brett

Brett Tofel
(802) 765-0440

**Comment by alexcherpi** [comment]
I think that it is correct.
With which sample was it? And what is it with the other bebop sample?

**Comment by bentito** [comment]
This is for Unix BebopDecodeStream. I can try other later.
