### ISSUE TITLE
JSPilotingNewAPI : connection lost (too long time without reception)

### ISSUE THREAD

**Issue by cromagn** [Parrot-Developers/Samples#52]
Ciao, I'm playing with the JSPilotingNewAPI sample, but some problem here.
When i run it on my Linux box dont work. Only some noise coming from my Jumping Sumo.
Commenting out the ihm i got a some log but appairs a *"connection lost (too long time without reception)"* error.
Following the full log, can you provide me a tip ?
br  & thks
carlo

*[INF] SDKExample | 06:43:33:064 | main:102 - -- Jumping Sumo Piloting --
[INF] SDKExample | 06:43:33:069 | main:140 - Do you want to write image files on your file system ? You should have at least 50Mb. Y or N
N
[INF] SDKExample | 06:43:37:345 | main:150 - You did not choose to write image files.
[INF] SDKExample | 06:43:37:345 | main:163 - - init discovey device ... 
[INF] SDKExample | 06:43:37:346 | main:170 -     - ARDISCOVERY_Device_InitWifi ...
[INF] SDKExample | 06:43:37:346 | main:205 - - delete discovey device ... 
[INF] SDKExample | 06:43:37:346 | main:236 - - set Video callback ... 
[INF] SDKExample | 06:43:37:346 | stateChanged:345 -     - stateChanged newState: 1 .....
[INF] ARNETWORKAL_WifiNetwork | 06:43:42:377 | ARNETWORKAL_WifiNetwork_Receive:825 - connection lost (too long time without reception)
[INF] SDKExample | 06:43:42:377 | stateChanged:345 -     - stateChanged newState: 4 .....
[INF] ARCONTROLLER_Device | 06:43:42:377 | ARCONTROLLER_Device_StartRun:2693 - Start failed or canceled.
[INF] SDKExample | 06:43:42:377 | stateChanged:345 -     - stateChanged newState: 4 .....
[INF] SDKExample | 06:43:43:741 | stateChanged:345 -     - stateChanged newState: 0 .....
[ERR] ARCONTROLLER_Device | 06:43:43:741 | ARCONTROLLER_Device_StartRun:2701 - Start fail error :start canceled
[ERR] SDKExample | 06:43:43:742 | main:270 - - deviceState :0
[ERR] SDKExample | 06:43:43:742 | main:271 - - error :No error
[INF] SDKExample | 06:43:43:742 | main:331 - -- END --*

**Comment by djavan-bertrand** [comment]
Hi cromagn, 

Are you connected with your computer to the Jumping Sumo Wifi ?

Regards, 
Djavan

**Comment by cromagn** [comment]
Ciao Djavan, yes it was connected.telnet working. Let me know how to' investigate in deep.really thks for your help. Carlo

**Comment by cromagn** [comment]
Not a code problem in my opinion but...network firewall somewhere in my dev chain...Lost incoming UDP traffic from parrot to PC...Tomorrow try to test on a clean linux box

**Comment by cromagn** [comment]
Confirmed network issue on vmware. Using a NAT connection from the virtual machine to the host *dont work*. Use a *bridged connection* to the host and everything run smooth!
