### ISSUE TITLE
Connecting Bebop 2 to Access Point

### ISSUE THREAD

**Issue by bellz867** [Parrot-Developers/Samples#62]
Hello,
We are trying to connect the Bebop 2 to an ap using the previously discussed script in  [https://github.com/Parrot-Developers/Samples/wiki/Convert-Bebop-to-client-instead-of-access-point](url) for the Bebop 1. Unfortunately attempts to do this have failed with the Bebop 2 but we have had success with Bebop 1. Has anyone else tried this and do you know the solution?
Thank you for your time.

**Comment by djavan-bertrand** [comment]
Hi, 

As this is not part of the SDK and this is not officially supported by our products, we can't provide you any help on that. 
However, you can try asking the community on our [developer forum](http://forum.developer.parrot.com/).

Best regards, 
Djavan
